# Una breve intro a jupyter notebook

Da https://www.dataquest.io/blog/jupyter-notebook-tutorial/:

<i>Jupyter notebook integra codice e output in un solo documento combinando visualizzazione, testo, formule, ecc...  
 Quest'organizzazione del contenuto favorisce uno sviluppo rapido e interattivo...</i>
 


### Kernel e celle

Ci sono due elementi fondamentali che dovete imparare a conoscere: le <font color="red">celle</font> ed il <font color="red">kernel</font>

- Un kernel è un "motore computazionale" che esegue del codice
- Una cell è un contenitore di testo che viene visualizzato nel notebook oppure di codice che viene eseguito dal kernel.

### Celle

Siamo interessati a due tipi di celle in particoalre:

- <i>cella di codice</i>, che contiene codice che viene eseguito dal kernel producendo un output visualizzato subito sotto 
- <i>cella Markdown</i> che contiene testo formattato appunto in linguaggio Markdown e ne visualizza l'output

#### Le celle inserite fino a qui sono tutte di tipo Markdown!

#### Per visualizzare il testo in Markdown basta cliccare due volte sulla cella...
#### Proviamo ad aggiungere una nuova cella di testo:
- Insert cell below
- Run!

# PROVA
## PROVA
### PROVA
#### PROVA

### Kernel

Quando viene fatto il run di una cella di codice, le istruzioni vengono eseguite dal kernel e l'output prodotto viene "ritornato" alla cella che lo visualizza. <font color="blue"> Lo stato del kernel persiste nel tempo e tra le varie celle, quindi si riferisce all'intero documento e non alle singole celle</font>

#### Usiamo una cella di codice

In [2]:
# In una cella di codice possiamo inserire dei commenti, ossia righe che vengono ignorate dal kernel durante
# l'esecuzione del codice
print('Hello world!')

Hello world!


### Let's code

In [3]:
# Prima di tutto, dobbiamo importare le librerie che ci servono
import numpy as np

In [5]:
# Definiamo una matrice esempio e procediamo a selezionarne porzioni separate
matrice = np.array([[0,1,2,3,4,5], [10,11,12,13,14,15], [20,21,22,23,24,25],
                    [30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])

print("La matrice è composta come segue:")
print(matrice)


La matrice è composta come segue:
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [5]:
# Quali sono le dimensioni della matrice?
print(np.size(matrice));
print(np.shape(matrice));

36
(6, 6)


### Maneggando immagini (matrici!!!) ci troveremo spesso a dover accedere a sottoparti di esse. Impariamo come si fa!

In [7]:
print('Selezionamo la prima colonna ...')
print(matrice[:,0])
print('Selezionamo la prima riga ...')
print(matrice[0,:])

Selezionamo la prima colonna ...
[ 0 10 20 30 40 50]
Selezionamo la prima riga ...
[0 1 2 3 4 5]


Come possiamo selezionare differenti porzioni di una matrice? 
Proviamo qualche esempio. 

In [10]:
matrice[0,1:6]


array([1, 2, 3, 4, 5])

In [11]:
matrice[4:,4:]

array([[44, 45],
       [54, 55]])

In [12]:
matrice[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [ ]:
matrice[2:3:2,::2]

#### Come definire delle funzioni

In [6]:
# definiamo una funzione che dato x calcola y = x*x + 2x -1
def calcolaF(x):
    y = x*x+2*x-1
    return y

In [7]:
# Adesso usiamo la funzione per generare una nuova matrice a partire da quella che abbiamo
matrice2 = np.zeros(np.shape(matrice))
np.shape(matrice2)

(6, 6)

In [8]:
for i in range(0,np.size(matrice,0)):
    for j in range(0,np.size(matrice,1)):
        matrice2[i,j]=calcolaF(matrice[i,j])

In [9]:
print(matrice2)

[[-1.000e+00  2.000e+00  7.000e+00  1.400e+01  2.300e+01  3.400e+01]
 [ 1.190e+02  1.420e+02  1.670e+02  1.940e+02  2.230e+02  2.540e+02]
 [ 4.390e+02  4.820e+02  5.270e+02  5.740e+02  6.230e+02  6.740e+02]
 [ 9.590e+02  1.022e+03  1.087e+03  1.154e+03  1.223e+03  1.294e+03]
 [ 1.679e+03  1.762e+03  1.847e+03  1.934e+03  2.023e+03  2.114e+03]
 [ 2.599e+03  2.702e+03  2.807e+03  2.914e+03  3.023e+03  3.134e+03]]
